### ISSUE TITLE
Update Training Syllabus to OWASP Top 10 2021

### ISSUE THREAD

**Issue by danieldavidson** [OWASP/SecureCodingDojo#107]
When I'm incorporating SecureCodingDojo lessons in to my security champions curriculum, I must routinely reference a mapping between OWASP Top 2017 and 2021 to see where the lessons fit. I've updated the SecureCodingDojo Training Syllabus [here](https://github.com/danieldavidson/SecureCodingDojo-Wiki/blob/main/Training-Syllabus.md) with the OWASP Top 10 2021 based on the [CWE VIEW: Weaknesses in OWASP Top Ten (2021)](https://cwe.mitre.org/data/slices/1344.html) version 4.8.

You're welcome to apply my [commit](https://github.com/danieldavidson/SecureCodingDojo-Wiki/commit/bc9254792b3cbe8a8aa92cb9dd2adfb679f885bc) to update the wiki here.

**Comment by paul-ion** [comment]
Thank you @danieldavidson ! I have updated the Syllabus. Is not a 1 to 1 match but mostly agreeing with your classification. For example the Reliance on Untrusted Input challenge maps better to Broken Access Control because the attacker gives themselves admin rights. Please have a look and let me know what you think.

**Comment by danieldavidson** [comment]
I'm on board with most of your changes. The only one I disagree with is _Blue Belt : Unrestricted Upload of File with Dangerous Type_ as [A08](https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/) Software and Data Integrity Failures. My understanding of that module is that the dangerous file isn't impacting the integrity of the web app itself, but is only being handled in an insecure way. Which to me maps better to [A04](https://owasp.org/Top10/A04_2021-Insecure_Design/) Insecure Design. Either way, I appreciate you making the update.

If you could update the column header that would be great too. ;)

**Comment by paul-ion** [comment]
Deal. Thanks again for the input!
