### ISSUE TITLE
Access to enhanced Modules

### ISSUE THREAD

**Issue by xrayn** [OWASP/SecureCodingDojo#110]
I am currently evaluating the software for a course in Secure Coding. Is there a quick way to check out the more advanced modules, like the hackerden (SecondDegreeBlackBelt) or the blue/red teaming?

I somehow figured out how to enable the modules inside the portal, bute the module keeps telling me:

**Play Link and Instructions**
The play link has been provided to you when solving the previous challenge. If you have missed it read the challenge description carefully and try to figure out what it is.

Once you were able to complete the challenge you can generate a code which you can submit below.

I tried to have a look in the code, but could not figure it out quickly, how to access these modules properly.

Do I have to complete the BlackBelt and then the links become suddenly visible, or do I need to do some more configuratin?

**Comment by paul-ion** [comment]
Dockerizing the Second Degree blackbelt is a planned but yet incomplete project. For the time being this module is not available.
