### ISSUE TITLE
Play button for Red Team module not available?

### ISSUE THREAD

**Issue by sdushantha** [OWASP/SecureCodingDojo#113]
Hi, I managed to complete Security Code Review Ninja and Black Belt but it seems like I am not able to work on the Red Team module. This is because the play button is not visible 

THe instance that I am using is hosted by OWASP: https://securecodingdojo.owasp.org/

![image](https://user-images.githubusercontent.com/27065646/219634325-d2f1e085-ad19-4068-a201-f4db350fd80d.png)

**Comment by paul-ion** [comment]
The Red Team and Blue Team modules are not currently available as self paced training.

**Comment by sdushantha** [comment]
@paul-ion Where could I find the non-self-paced training?
