### ISSUE TITLE
Will it support AAD integration to login

### ISSUE THREAD

**Issue by Jun-Zhu-Trend** [OWASP/SecureCodingDojo#114]
current it current ADFS method , will it support AAD authentication method ？

**Comment by Jun-Zhu-Trend** [comment]
or add support for LDAPs ?
thank you.

**Comment by paul-ion** [comment]
LDAP support is available. See: https://github.com/OWASP/SecureCodingDojo/blob/main/trainingportal/config.json.sample#L42
