### ISSUE TITLE
Development changes are not pushed into the platform

### ISSUE THREAD

**Issue by Rogatiq** [OWASP/SecureCodingDojo#116]
I have a problem with the development setup. After running the devsetup script. Everything runs without errors and the tests past with no errors. But if I change the code the changes are only seen when I debug server.js 

Also the dojo user is created, but I can't log in with that account.

**Comment by Rogatiq** [comment]
The problem comes when running the buildingTrainingportal script. When npm install is run, package.json and package-lock.json can't be located although they are in the folder that the command is run.

**Comment by paul-ion** [comment]
@Rogatiq this should new be solved by recent changes to docker-compose.yml. Simply do a docker-compose build in the root directory and all changes should be built into the containers when you run with docker-compose up -d.
