### ISSUE TITLE
Unknown Error after completing CSRF challenge on Blackbelt module

### ISSUE THREAD

**Issue by nate-242** [OWASP/SecureCodingDojo#118]
I completed the "Purple Belt : Cross-Site Request Forgery (CSRF)" challenge but when I submit the code (after using the salt to generate it like with all other challenges) I constantly get an unknown error. I have tried restarting my machine, walking away and trying again a day later, etc etc. but nothing seems to work for this error. It has persisted for 2 days so far.

![image](https://user-images.githubusercontent.com/114825169/233066480-5827b684-b515-4315-81d8-bc33a6ff7525.png)

**Comment by paul-ion** [comment]
I believe this issue should be resolved at this point.
