### ISSUE TITLE
502 Bad Gateway error after import a CSV file to get a report

### ISSUE THREAD

**Issue by gianoni** [OWASP/SecureCodingDojo#119]
The report has a issue after importing the CSV file and choose which module you want a report. Last Friday, 6/16, I ran the report and as a result I put the server down with a bad gateway error (502). I was not sure that was because of me. Then, on Monday, the server was back to life, and I tried to run the report again, and, the server goes down. So, I realize that was me that  put the server down after ran the report.
As soon the server and application get back to life, I will be able to insert the screenshots of the report option. But this time, without the CSV file, and without put the server down again.

![Bad_Gateway](https://github.com/OWASP/SecureCodingDojo/assets/68572112/13230dc9-222d-438c-9f68-33a89b3102bb)

**Comment by gianoni** [comment]
Here you can see the option on the Menu, and the CSV file that triggers the error.

![report_error](https://github.com/OWASP/SecureCodingDojo/assets/68572112/c0185125-465a-4799-b84e-c146afa05cb9)
[CSV_FILE.csv](https://github.com/OWASP/SecureCodingDojo/files/11834081/CSV_FILE.csv)

**Comment by paul-ion** [comment]
Thank @gianoni . Fixed by this commit: https://github.com/OWASP/SecureCodingDojo/commit/68ad5739b014e4b3618c2ce912212c6bebd61ec0
