### ISSUE TITLE
Play button not displayed in Red Team/Blue Team lessons

### ISSUE THREAD

**Issue by AlexisCesar** [OWASP/SecureCodingDojo#120]
The play button is not showing in any of the challenges within the Red Team or Blue Team lessons. Screenshot:
![image](https://github.com/OWASP/SecureCodingDojo/assets/42656077/fa814809-996f-41cf-ae09-95a2ce33af16)

**Comment by paul-ion** [comment]
This is by design @AlexisCesar . Those modules are not yet available for self-paced learning. Please stay tuned.
