### ISSUE TITLE
Connection timed out - Error code 522

### ISSUE THREAD

**Issue by WolfMan12333** [OWASP/SecureCodingDojo#146]
Hi, I wrote about this error code to someone I think here. It is happening when I want to connect to this website: https://securecodingdojo.owasp.org

Will anyone help?
<img width="834" alt="Screenshot 2024-02-14 at 08 33 15" src="https://github.com/OWASP/SecureCodingDojo/assets/1895944/ebb87fd2-bcd4-49e7-b445-463b38550d9b">

Best regards

**Comment by paul-ion** [comment]
Hi @WolfMan12333 the Dojo Demo site runs out of resources sometimes. You can also deploy your own instance, see the README.

**Comment by paul-ion** [comment]
PS should be back up now
